resources:
  - url: http://127.0.0.1:5000/latest-camera-card.js
    type: module
views:
  - cards:
      - type: custom:latest-camera-card
        name: Latest Camera Card Development
        entity: sun.sun
        test_gui: true
